package ch.andu.cakeWars.files;

import org.bukkit.Bukkit;
import org.bukkit.Location;
import org.bukkit.World;
import org.bukkit.configuration.Configuration;

import java.util.ArrayList;
import java.util.List;

public class Locations {

    private static FileManager fileManager;
    private static Configuration cfg;
    public Locations(FileManager fileManager){
        this.fileManager = fileManager;
        cfg = fileManager.getConfig();
    }

    public void setLobbySpawn(Location location){
        saveLocation("lobby","spawn",location);
    }

    public Location getLobbyspawn(){
       return loadLocation("lobby","spawn");
    }

    public void setMapSpawn(String map ,Location location) {
        String spawn = ".location";
        saveLocation(map, spawn, location);
    }

    public Location getMapSpawn(String map) {
        String spawn = ".location";
        return loadLocation(map, spawn);

    }

    public void setMapGenerator(String map, String type, Location location) {
        String path = map + "." + type;
        List<String> locations = cfg.getStringList(path);


        locations.add(serializeLocation(location));
        cfg.set(path, locations);

        fileManager.saveConfig();
    }

    public List<Location> getMapGenerators(String map, String type) {
        String path = map + "." + type;
        List<String> serializedLocations = cfg.getStringList(path);
        List<Location> locations = new ArrayList<>();

        for (String serialized : serializedLocations) {
            Location loc = deserializeLocation(serialized);
            if (loc != null) {
                locations.add(loc);
            }
        }
        return locations;
    }

        public void setMapTeamSpawn(String map, String team, Location location){
        String spawn = ".spawn";
        saveLocation(map,"."+team+spawn,location);

    }

    public Location getTeamSpawn(String map, String team){
        String spawn = ".spawn";
        return  loadLocation(map,"."+team+spawn);
    }

    public void setMapTeamCake(String map, String team, Location location){
        String spawn = ".cake";
        Bukkit.broadcastMessage("GAMING"+location+map+team);
        saveLocation(map,"."+team+spawn,location);
    }

    public Location getTeamCake(String map, String team){
        String spawn = ".cake";
        return loadLocation(map,"."+team+spawn);
    }







    private void saveLocation(String paths,String name, Location location) {
        //methode generated by ChatGPT, i was to lazy
        String path =paths + name;
        cfg.set(path + ".world", location.getWorld().getName());
        cfg.set(path + ".x", location.getX());
        cfg.set(path + ".y", location.getY());
        cfg.set(path + ".z", location.getZ());
        cfg.set(path + ".yaw", location.getYaw());
        cfg.set(path + ".pitch", location.getPitch());
       fileManager.saveConfig();
    }

    public Location loadLocation(String paths, String name) {
        String path = paths + name;
        if (!cfg.contains(path)) return null;

        World world = Bukkit.getWorld(cfg.getString(path + ".world"));
        double x = cfg.getDouble(path + ".x");
        double y = cfg.getDouble(path + ".y");
        double z = cfg.getDouble(path + ".z");
        float yaw = (float) cfg.getDouble(path + ".yaw");
        float pitch = (float) cfg.getDouble(path + ".pitch");

        return new Location(world, x, y, z, yaw, pitch);
    }

    private String serializeLocation(Location location) {
        return location.getWorld().getName() + "," +
                location.getX() + "," +
                location.getY() + "," +
                location.getZ() + "," +
                location.getYaw() + "," +
                location.getPitch();
    }

    private Location deserializeLocation(String str) {
        if (str == null || str.isEmpty()) return null;
        String[] parts = str.split(",");
        if (parts.length != 6) return null;

        World world = Bukkit.getWorld(parts[0]);
        if (world == null) return null;

        double x = Double.parseDouble(parts[1]);
        double y = Double.parseDouble(parts[2]);
        double z = Double.parseDouble(parts[3]);
        float yaw = Float.parseFloat(parts[4]);
        float pitch = Float.parseFloat(parts[5]);

        return new Location(world, x, y, z, yaw, pitch);
    }

}
